### PR TITLE
add case-insensitive-sort command

### PR DESCRIPTION
**Pull request by thancock20**
Adds a case-insensitive-sort command. This - along with the sort and reverse commands - means I can uninstall the Lines package. (I don't use unique or shuffle)

### CODE REVIEW

**Comment by t9md** [comment]
I want sort come first in name like SortCaseIntensively or SortWithCaseIntensive

**Comment by thancock20** [comment]
I've changed the name to SortCaseInsensitively.

**Comment by t9md** [comment]
@thancock20 I modified your code a bit and wrote test spec.

Could you confirm the behavior described in this test-spec fit in your expectation?

https://github.com/t9md/atom-vim-mode-plus/commit/79d143dd60d70fd4e2c1730aa8ea681a38014168

**Comment by thancock20** [comment]
Yes, that looks right.

**Comment by t9md** [comment]
Already released as v0.78.0, thanks for contribution!

**Comment by thancock20** [comment]
You're welcome, and thank you for such a great package!

**Pull request merged**
