### PR TITLE
Auto Indent On Paste (Atom setting) not respected with put from vim registers

### PR DESCRIPTION
**Pull request by apazzolini**
Hi, thanks for all of your hard work on this project!

I'm running into a discrepancy between normal Atom behavior and vim-mode-plus behavior. Given some sample code with a few levels of indentation:

```js
if (someCondition) {
  if (otherCondition) {

  }
}
console.log('hi');
```

if I cut/copy the `console.log` line, go into the inner-most block, and paste, Atom follows the `Editor/Auto Indent On Paste` setting and I end up with

```js
if (someCondition) {
  if (otherCondition) {
    console.log('hi');
  }
}
```

If I do the same thing with Vim keybindings `dd` and then `p` (or `P`), the indent level from the original line is maintained:

```js
if (someCondition) {
  if (otherCondition) {
console.log('hi');
  }
}
```

Standalone vim puts the line in the expected/desired spot. Is there a way to make vim-mode-plus follow this behavior as well?

### CODE REVIEW

**Comment by apazzolini** [comment]
I actually went ahead and implemented this instead :)

**Comment by t9md** [comment]
first of all, what I see in pure-Viim behavior is NOT what you are saying.
`console.log('hi')` line pasted without auto-indent.

Do you still can see the behavior you mentioned with `vim -u NONE`?

**Comment by apazzolini** [comment]
You're correct - it's not the default behavior. I have a [plugin](https://github.com/sickill/vim-pasta) providing that functionality (must have installed it forever ago because I can't remember that not being the behavior). 

I'm happy to put this behind a different flag if you'd like, but `editor.autoIndentOnPaste` does exactly this behavior:



With the changes in this pull request, we get the following. Note that Atom doesn't trigger auto-indent over the full range (last example). It calculates the necessary adjustment for the first line you're about to paste and adjusts the pasted text by that adjustment. I replicated that same behavior.



Thoughts?

**Comment by t9md** [comment]
So this is enhancement to bring `vim-pasta` like feature to vmp.

- I want this separate command like `put-with-autoindent-only-when-linewise` or `putWithAutoIndent`.
  - Via extending existing `Put` command.
- What happens when multi-line-autoindented-code was `p`-ed from clipboard. It won't break already indented text?
  - This is one reason I prefer sparate-command approach rather than differentiate existing `p` via config option
- When indent auto-adjusted flash(flashing effect on pasted area) works as expected?
- Can you use `@editor.autoIndentBufferRows(start, end)` for this purpose to avoid manual indentation adjust logic as small as possible.

**Comment by apazzolini** [comment]
Yes, it effectively brings `vim-pasta` features (which Atom implements natively with autoIndentOnPaste).

- I can create this as a separate command, no problem. Will submit another commit for that tomorrow.
- If you `p` in code that has indents, it will keep the exact indentation you originally had. It will just shift the entire block left/right appropriately.
- Yes, I see a flash on the lines when the paste happens.
- Using `autoIndentBufferRows()` actually changes the behavior. If you look at the last example in the GIF above, you can see that the second `console.log` statement is indented incorrectly (very far to the right). When we adjust with this feature, we should respect the original indentation, not auto indent the `p`ed lines. It's a subtle difference:

**Comment by t9md** [comment]
OK, understand. and for flash it's understandable since it's `linewise`, as long as lines are changed before and after adjustment, it nothing to do for flash range.

Thanks for clarification, and I'm OK to merge if it kept separated and opt-in feature via custom keymap (or config for auto set keymap as I'm experimenting in #729?)

**Comment by apazzolini** [comment]
Ok, this is now on its own commands, `put-after-with-auto-indent` and `put-before-with-auto-indent`.

This is actually pretty nice to have separate - for my personal Atom I keymapped `cmd+alt+p` to normal put and `p` to the auto-indenting version. Sometimes you don't want it to auto indent (mostly in languages without curly braces), and now we have the option.

I also added an `ensureOperation` method to `spec-helper.coffee` since I didn't see a way to test commands that didn't have a default keymapping. Let me know if you already had that built and I overlooked it.

**Comment by t9md** [comment]
I rewrite a lot to make me understand what is doing.
This doesn't mean your code have some problem.
I rewrite code very frequently including code I wrote by myself.
Since I have to maintain whole vmp code alone and still I'm actively rewriting fundamental part which affect all operator, motion, text-object.
So having clear understanding to whole code base is very important.
I'm NOT prioritized to keeping clean commit history at least this project.
Hope you understand my background.

**Comment by t9md** [comment]
Btw this feature is very useful, thanks for nice enhancement!

**Comment by apazzolini** [comment]
Yup, no worries - this was both the first Atom and coffeescript code I've touched, so I'm sure I didn't do things the best way. I saw the changes you made and it's definitely better, I didn't realize `setIndentationForBufferRow` existed.

Thanks for cleaning it up and merging! This was one of the main things keeping me on normal vim instead of Atom.

**Pull request merged**
