### PR TITLE
Automatically adjust indentation level when inserting newlines

### PR DESCRIPTION
**Pull request by apazzolini**
If the editor setting `Editor/Auto Indent` is turned on, we can optimize cursor position after newlines are inserted.

Before pull request (cursor denoted by `|` with indent level of 4 spaces)

```javascript
if (something) {

|

}
```

Pressing `O` results in

```javascript
if (something) {

|


}
```

After pull request:

```javascript
if (something) {

|

}
```

Pressing `O` results in

```javascript
if (something) {

    |


}
```

The change to the test reflects what the behavior in Vim does as far as I can tell. Let me know if I'm misinterpreting something.

### CODE REVIEW

**Comment by t9md** [comment]
Why this fix is required?, `o` and `O` already respect `editor.autoIndent` setting.
So spec already passed with autoIndent-ed result.
What you fixed in spec is not correct result.
If it's not work in your environment, you might overriding `editor.autoIndent` for specific language(e.g. language-javascript have autoIndent setting to override this value for per-language)

**Comment by apazzolini** [comment]
I agree that `o` and `O` respect `editor.autoIndent` when the surrounding line is non-empty, but it fails with empty lines around it. 

Here's what I'm seeing on a completely fresh Atom installation with only vim-mode-plus installed. Are you able to replicate this?

**Comment by t9md** [comment]
I see what point you are saying DIFFERENT THAN VIM.
The diff is when cursor is at blank-row.

- In pure-Vim it pick desirable level.
- In Atom, indentation is seems to be calculated based on current line's indentation. and cursor is at blank-row, it keep indentation level=0

I know Atom's behavior is a bit oversimplified.
I once tried manual indentation in Atom for vmp, but from my experience trying to do it manually was bad idea.

So I can't accept manual adjustment unless it's have obvious benefits, fix.
As I mentioned above, I don't think your modification for test spec is not necessary

So I want to understand what the issue is in the first place.


Btw, I'm glad you added test spec, and happy to use some spec helper by new contributer other than me!

**Comment by t9md** [comment]
> Btw, I'm glad you added test spec, and happy to use some spec helper by new contributer other than me!

Oh, I'm saying for your another PR, not this one.

**Comment by apazzolini** [comment]
I understand if you don't want to have this logic in the default `o`/`O` commands. Should I move this to a separate command like I'll be doing for the put refactoring?

I can also add a check to only do the indenting logic if the line you were on is `''` since that's the only time I've seen the problem.

The reason for the test spec change is I think the test spec is incorrect - with autoIndent, I think it should indent to match the suggested indent for the line. But, if I limit the logic to blank lines, I can revert the spec change.

**Comment by apazzolini** [comment]
OK, made the updates. 

We now use `editor.autoIndentBufferRow()` instead of manually adjusting the indent. We also only do this if we detect that the line above is the empty string, so previous spec change is reverted.

**Comment by t9md** [comment]
Minor changed for following behavior(following is original behavior in your PR).

# adjustIndent is done only for lastCursor, so in multi-cursor situation, non-last-cursor was not handled.

multi-cursor-o-indent


# For indent based lang like coffeescript or python(I haven't checked though), new behavior was not necessary improvement

When cursor is at method name, `O`, was indented, because it's empty row check is done against row above(line 187 is empty in this GIF).
This is pure-Vim behavior, but I don't like this, so new behavior is when current row is empty, it try to autoIndent.
This mean, when Atom already did autoIndent when `insertNewlineBelow` or `insertNewlineBelow`, vmp do nothing since that row is non empty(atom did auto-indentation when inserting new-line).

indent-coffee

Specifically this tweak is not applied in multi-cursor situation, in multi-cursor, since Atom's `editor.insertNewlineBelow`, `editor.insertNewlineAbove` determine `shouldAutoIndent` based on last-cursor's row. We can fix this too but I won't this is bug or limitation of atom-core.

**Pull request merged**
