### PR TITLE
Implement setting back-quote (and single-quote) Mark on jump movement

### PR DESCRIPTION
**Pull request by plbowers**
reference https://github.com/t9md/atom-vim-mode-plus/issues/384

### CODE REVIEW

**Comment by plbowers** [comment]
Apologies - it looks like I forgot to go back to my master branch after implementing allow-repeat-search-on-incremental

This means the change in motion-search.coffee will cause a conflict if you merge them separately. The easiest solution would be to just delete that PR and merge this PR, but then you don't have a nice history of it. Your call.

**Comment by t9md** [comment]
I need explanation what this PR is doing with short explanation.
And hope not including unrelated PR in one PRs.
Need spec.

I appreciate your contribution, but I want to use my time for me, so If you can, please do cleanup things by yourself.

**Comment by plbowers** [comment]
Hitting back-quote twice now takes you to the location prior to the previous jump-movement.

Hitting single-quote twice is largely the same but takes you to the start of the line rather than the exact location within the line.

Both standard vim features and very useful in different scenarios.

I have not implemented this for all jump-motions because the remaining jump-motions () do not seem to be implemented or not implemented in a way I recognize.

Reference your comment when you put this item in the TODO list: https://github.com/t9md/atom-vim-mode-plus/issues/384#issuecomment-248496562

**Comment by plbowers** [comment]
Cleanup completed. The PR should reference only changes related to this feature, as requested.

**Comment by t9md** [comment]
close in favor of #477

**Pull request closed without merging**
