### PR TITLE
Improve perfomance for f, F, t, T

### LINKED ISSUE #435: f and t commands are too slow
When using `f` or `t` command to jump to a certain place in the line, it takes a notable amount of time to get there comparing to other commands, which can be a bit annoying.

Hope there could be a faster solution for this. Thanks.

- Atom version info(`1.11.1`)
- vim-mode-plus version (`0.60.0`)

### PR DESCRIPTION
**Pull request by t9md**
WIP
Trying to fix #435 

Affects all operation, which read user-input from input-mini-editor.

Things are not simple, I have to consider following.

1. Is performance improved?
2. Is this work when user override keymap for prefix(e.g. define keymap map for `f j`).
Currently when user defined `f` prefixed keymap, it breaks `f` command itself(#260).
Because atom/atom-keymap#132 was merged, 1.12.0-beta3 have no issue.
But when I don't use existing hidden-input, this problem re-appear.
So take this into consideration to determine which approach is good.
3. Is it simple and can maintain in future?

### CODE REVIEW

**Comment by t9md** [comment]
## 0. Performance result

For 500 times `f l`.(Not pure performance, involves test spec dsl, jasmine overhead).
```
== 1. Current [read-hidden-inpt]
[time-end] testPerformanceOfHiddenInput: 6776.405ms
[performance.now] took 5479.420000000002 msec

== 2. Read user-input through keymap
[time-end] testPerformanceOfKeybind: 5028.319ms
[performance.now] took 4811.139999999999 msec

== 3. Read user-input from `keydown` event listne directly
[time-end] testPerformanceOfHiddenInput: 4521.100ms
[performance.now] took 4664.419999999998 msec
```

2nd: In this result, 2nd approarch wins, but in most-case 3rd approach was fastest as far as I checked.
```
== 1. Current [read-hidden-inpt]
[time-end] testPerformanceOfHiddenInput: 5649.881ms
[performance.now] took 5407.104999999996 msec

== 2. Read user-input through keymap
[time-end] testPerformanceOfKeybind: 4470.972ms
[performance.now] took 4271.725 msec

== 3. Read user-input from `keydown` event listne directly
[time-end] testPerformanceOfHiddenInput: 4504.424ms
[performance.now] took 4416.335000000006 msec
```

## 1. Current [read-hidden-inpt]

Speed: rank3
Issue-with-f-prefixed-keymap: OK(from 1.12-beta).

Pros.
- Easy to understand, feel natural to read user-input from mini-editor
- Can add mini-editor specific commands and keymap
- Can support multi-byte char(not inpotant for `f` case though)

Cons.
- **Slow**

## 2. Read user-input through keymap

Speed: rank2
Issue-with-f-prefixed-keymap: OK.

Cons.
- Not intuitive
- Cannot read multiple char at-once.
- No multibyte-char, no custom-command, keymap

## 3. Read user-input from `keydown` event listne directly

Speed: rank1
Issue-with-f-prefixed-keymap: NG.

Cons.
- Not intuitive
- Cannot read multiple char at-once.
- No multibyte-char, no custom-command, keymap

**Comment by bronson** [comment]
So, most are a 25% speedup, with one at 30%?

That's definitely an improvement, but it doesn't seem like it would make a big difference...  When you use them, do they feel better than the numbers would indicate?

**Comment by t9md** [comment]
Yes I feel big diff in actual user experience. 

I'll vote 2nd(read through keymap) approach for speed and work-well-with-user-defined-keymap.

**Comment by bronson** [comment]
That's a relief.  Really looking forward to when it's ready to ship.

**Comment by t9md** [comment]
```
[500 times]
== old
[time-end] : 4770.959ms
== new
[time-end] : 3654.973ms


[1000 times]
== old
[time-end] : 15073.743ms
== new
[time-end] : 13199.336ms
```

**Comment by bronson** [comment]
Wow, that's fantastic.  Feels much faster than 30%.

**Comment by t9md** [comment]
Oh you tried? very quick!

**Comment by bronson** [comment]
I want.  :)

**Comment by t9md** [comment]
Umm, this PR itself is good.
But I noticed, original `vim-mode` is not so slow in spite of it use mini-editor(same approach with vmp's slow input).

I'll investigate further.
If min-editor approach can improve performance, it's best solution I think.

**Comment by ugoa** [comment]
@t9md  Just tried out the original `vim-mode` and those commands run at a quite decent performance. Thank you for your effort and good luck!

**Comment by t9md** [comment]
I played with vmp's original-slow-input-element to find out other approach to improve performance.
And learned a lot. What I learned is vim-mode-plus is basically slow than vim-mode.
There is several reason.
- Code is separated to several module. operationStack is heavier than vim-mode.
- vim-mode-plus have Base class and constructor -> initialize lifecycle
- new and throwing away object on each execution is sometimes faster than refusing it.
- original-slow-input use panel.show, it's add extra time
- registering event hook in `Base::focusInput()` add extra time.

I think I can gradually remove above performance-affect-code.
Ultimately inlining these separated logic make code faster but this also greatly reduce maintainability/readability.

So for now, I'll keep improved-faster-input to get better UX immediately.
And I'll continuously look and evaluate what I can do to improve responsiveness.
It's gradual process.

**Pull request merged**
