### PR TITLE
Navigation for tree-view

### PR DESCRIPTION
**Pull request by SchDen**
Vim mode way navigation in [atom/tree-view](https://github.com/atom/tree-view)

### CODE REVIEW

**Comment by t9md** [comment]
I like this just want to try.
Thanks for nice PR!

**Comment by slavaGanzin** [comment]
There is nerd-treeview package that do a lot more. This shouldn't be coupled with vim-mode.

**Comment by t9md** [comment]
@slavaGanzin Yes, you are right, when I wrote above comment, I was drunk a bit :smile: .

@SchDen I like your keymap suggestion, but it should be fall into intividual `keymap.cson`.
I don't want to set aggressive keymap by default.

Btw I set this tree-view keymap in my keymap.cson and its great. Thanks for sharing this usefulness.

**Comment by SchDen** [comment]
Ok, welcome : )
My config hub https://github.com/SchDen/atom-config

**Pull request closed without merging**
